apiVersion: v1
kind: Service

metadata:
  name: javaapp-service
  labels:
    app: javaapp
spec:
  selector:
     app: javaapp

  ports:
  - port:  8080         #port that Service runnung
    targetPort:  8080   #port that container runnung

  type: LoadBalancer
