---
- hosts: k8s
  #become: true
  user: root
  
  tasks:
  - name:  deploy javaapp on kubenettes
    command: kubectl --kubeconfig /home/zonkol/.kube/config apply -f /home/zonkol/project/service-file.yml
